package com.example.springbootkeycloak.AdventOfCode;

import java.util.Map;

public class AdventOfCode1_2 {

    static String input ="four82nine74\n" +
            "hlpqrdh3\n" +
            "eightsevenhrsseven988\n" +
            "324pzonenine\n" +
            "fglpbone79fourvrgcmgklbmthree\n" +
            "fmbbkvthdcdmcjxzclk42six4\n" +
            "four22xcqsnvktnpfshtmm\n" +
            "qmfsccxsixfivelnmpjqjcsc1sixpfpmeight\n" +
            "eight1nine5nine9six\n" +
            "s4r91seven\n" +
            "6pspkslrnxpplkhgqlcqfour\n" +
            "sixeightnzrzgjvsrnmtqgx5\n" +
            "sixtwo1\n" +
            "h6\n" +
            "five8pbcsllrbvg787\n" +
            "dpfhfeight28onefourtwo\n" +
            "vxqbtkxjtwoz3seven\n" +
            "8ksrcjrcmpbq9rtvtvrbgljzqvbnxddnzt\n" +
            "mpftpsgp6fourvdmltwojd9\n" +
            "2fivetwosix\n" +
            "3qqx2\n" +
            "jsbdh16snnllpvvgnggfive5nhjpgdzh\n" +
            "4fmgmmbonegtsnqfdqt1pm\n" +
            "2onendvlmcrvzsnpr83nine\n" +
            "8ninelfhkhnqtdfour\n" +
            "8reight\n" +
            "84gnprjhr3eightsixsix\n" +
            "1nc7two\n" +
            "3zcgkgrnd1d4\n" +
            "nmfqfivervqkxmkdpnine51\n" +
            "1fdtrptkb3\n" +
            "nineone7kks\n" +
            "ninelzgncpeight966427\n" +
            "eightrsniner9\n" +
            "nine7two4\n" +
            "253slq\n" +
            "lkhthreetwo982rrc\n" +
            "fivegdsfnfour64sixtqfour\n" +
            "dkfdtgnine9\n" +
            "1six15ninebgnzhtbmlxpnrqoneightfhp\n" +
            "32fivefivexjvckfourseven5seven\n" +
            "onexxzvptxkn42eightvsdgszdjgp\n" +
            "three6sevennine\n" +
            "mvsrflqjsix22lhd2twodkltkmsk\n" +
            "threetnbfsfxxhseven51cjvmkvzkdhr2\n" +
            "11twoxjszm93\n" +
            "trr62fivedvktlheight19\n" +
            "4hxthreepqptvkkzmfsevenfourxeight\n" +
            "5shqhrjtdgsninepblpjprtqptz\n" +
            "ptwone9kzvjhhfive7qjsblztmfvthreeqrhhmbgjpqrgqhcgzntmvskhh\n" +
            "xltqzgqxbkq7krgnthtqbm3636\n" +
            "nvvxfxbgldrb2seven7twokxzbfkvptflnhlqjrthreeoneights\n" +
            "7fcvckqszbj\n" +
            "eight1ninethreeninenbmcsqtrl7\n" +
            "zkqmlqmtszrbvnjnvsevennine9sevenqjrlxqjlql\n" +
            "428\n" +
            "8seven16nineeight\n" +
            "24bkfzsrxjtbzbknqqxtfftzlnrkeight\n" +
            "two372eightnine\n" +
            "skxf5zpnmzqgvzjv9sixtwo\n" +
            "1fivedsghrseven4\n" +
            "8hmb75twotwo\n" +
            "2hsnpfourthree3h88cz\n" +
            "6qkqxszvghrdslpckhfivedlx\n" +
            "pnxvtbflleightjpfzlqxhr22ckjrnzhnbvdnj1xnfhmb\n" +
            "cdscn4xksngscvnseven\n" +
            "65oneightpln\n" +
            "ninesix11six41seven5twonesl\n" +
            "f411d\n" +
            "sixonedqppgfdfbthree1sj1sevenqhdjlg\n" +
            "eightsixhzshtg5oneone\n" +
            "tbhdgzphkkvbbclmhgvb3three\n" +
            "dpsxdfmzstpd7rzf3\n" +
            "kzpctbr3oneninevgcxcvsconeightgk\n" +
            "blmpjv6ltxfqsqfjnjgxtseven82\n" +
            "99four\n" +
            "onexsxs3sixdnfqlffjnnrfive\n" +
            "4sevenzdjvrqjlx33\n" +
            "brtbqvzcdtlkn83sevenmmtwo\n" +
            "5bnlmjtmeight\n" +
            "twotwofive2fqbfvqhp65eight\n" +
            "dstwoneninekfourphth4lrfjjrh\n" +
            "mqsndqcxt3\n" +
            "5mbfxskgnh1twoqbxfbcjkzf\n" +
            "6fourzdcmdl78pvxxjrplmtmvhh\n" +
            "3mzgttvpt8gvzoneseven21\n" +
            "8253fgfhpmponef8\n" +
            "nineninelhntskjvd25\n" +
            "1czbccmrlch27three\n" +
            "one4l5four\n" +
            "sixmcnsxf5two\n" +
            "onethree2five7vzhctscktrcx\n" +
            "14szp5fqtqfzcd\n" +
            "6cgpzjprtsjd8five4vjzfhgkbbf9\n" +
            "7gt\n" +
            "4lzx\n" +
            "fonexgjsnine8\n" +
            "1twomvdvdrrneight8fivenine\n" +
            "59eightthreesevenctwon5\n" +
            "2dxfivenqflqppm3bmtmblbkltwomc\n" +
            "36mplfgblgff6\n" +
            "threeseven8gf9sevennine85\n" +
            "hfssbghbnonesvdm7onekssjbthxjjvnqmcgmrcx\n" +
            "eightfrbrstlh8\n" +
            "eight34sevendlhvhszcnvdlvctkdzsgq\n" +
            "seven2eightmtsmflrx2three44rsk\n" +
            "fg6\n" +
            "mbf44\n" +
            "5926386nine\n" +
            "48vqvcffsq2eight7zktszfour\n" +
            "djstrfnqsixone8oneightc\n" +
            "5seventwoqtr3eight5\n" +
            "dttwo88three\n" +
            "8rdxmnrtmt\n" +
            "r2tzcbr867onetwo\n" +
            "2v489four2\n" +
            "vsmfszr5\n" +
            "84nxrm48\n" +
            "5cp4five51three\n" +
            "four3six3\n" +
            "4zglqmdngeight1sqb\n" +
            "3twosrlvbzfh6nkrhmnjqeightseven\n" +
            "eightgjhs276five\n" +
            "j15one683\n" +
            "hnnonefvhnxggtwoz2five\n" +
            "threeseven2fourkltqmthree\n" +
            "bmksn4\n" +
            "11ntrt\n" +
            "5tctbxqjcngdhffqqrjfive\n" +
            "vcstnf1\n" +
            "98tgzlvtwobjpxj6\n" +
            "one6j5hqgbvhtmsjkbt7mglhvjjxmtwo\n" +
            "1sixq\n" +
            "three8lbqdd38ljfourtwoccntjgnmv\n" +
            "two5msdsntdrjl4six15tdpnknrxnine\n" +
            "sevenzkbfmqxb2sixsevenbvnbxtxvfournine\n" +
            "1nzdfninednkhghlscsc\n" +
            "onefive3gvjsqqgx7seventhree\n" +
            "8dglgts4slg5sixninevzsj\n" +
            "dxdmkshgssevenfour967ninetwo\n" +
            "4ninevrhsbqnjtwo\n" +
            "358fiveseven\n" +
            "two8sixzt2\n" +
            "93ninefztjqrhdlxxsjnnflczbsjqpkrmsixtngxqk\n" +
            "ltpnkxtwoeightcfpjhthree5brzhffour\n" +
            "four3five6q645qxn\n" +
            "fourjxqghk6\n" +
            "8dznl428nine\n" +
            "1djftqndtmkcbptxs22\n" +
            "27one\n" +
            "543\n" +
            "qgtbvgnl4tzfgch7zqtmpsix\n" +
            "fourxfgqcsgxbg741922nine\n" +
            "two4sixmkvkftwo5one\n" +
            "lrlnnbdzr82g58fkgvfninezmqv\n" +
            "2xbkhjbrlztnphmcsfcln\n" +
            "2xlxksqkb\n" +
            "rcnzsrtfive9scnnvqx6kmkvgmxlpqtkmbjtvsfmvseven\n" +
            "6oneninekfpnbngn2\n" +
            "2nnxlthmxqc9eighttcznxdchdthree\n" +
            "dznqtbkgtwo5zpthvsnone\n" +
            "7nxjjzhfhpshccknpbpttrjhqkxmmssvtlxtmbxlhvtjczone5twonecf\n" +
            "96eight\n" +
            "7qvckkdtvzjd\n" +
            "14nine1two\n" +
            "eight87one8ncdzkptqrgtfclsevenc\n" +
            "8fourfive\n" +
            "jjqbpmp42589stwosix\n" +
            "vtrbqpv9sevenone1qlvmzkthnnsevenseven\n" +
            "pxnxptttxh6fourmbpcldrlfnjtcxtwoonefour\n" +
            "8njghfrsix82\n" +
            "gvns197fsgtwo\n" +
            "9sljnsix8\n" +
            "rnine7ninethreenjxnrqgzbxbtvrltbss\n" +
            "4stzbqg44f\n" +
            "3ninesevennvvdmgkxzmttcxfbsvjrg\n" +
            "eightsix3twofmnvs\n" +
            "one2fmzxnhhrnvlttxnhbrjsgjsqkvfn5\n" +
            "qz9ptnxfngfrh65bvvbhtsrsntczgj\n" +
            "qfvqfpb2txnxxd2fiventvznljcqj\n" +
            "fiveqvmzqlgzdbvqzjbllzeight5bgt\n" +
            "qggflvv753clcqqjqmngdm6onefour\n" +
            "3fourfiveeightbbgcgtwo857\n" +
            "one5nineeightg44\n" +
            "6zmqxcl16twofivedjxhzmhffive\n" +
            "jnnsixsixtwo2bgsnbrzlnlltb\n" +
            "six63oneightgdg\n" +
            "pftmhdnqdgfive1three42four\n" +
            "8hkcjlskh82\n" +
            "84\n" +
            "1ninefour9sxmppxjqqxpn\n" +
            "ndrgrhsp1gxcrfgxctv\n" +
            "fiverzmcmbqd78gqm\n" +
            "fiveeight4\n" +
            "vxktmrcdlsfiveoneftvqnnvjfour8sixlmldnrceight\n" +
            "hpfprllctdjtwo9ksszn8eightcfdbzz\n" +
            "nine5fourfbgf8one7t\n" +
            "8sqxm5\n" +
            "6fxcxhn\n" +
            "2prktdcvnine1\n" +
            "2vqrlpffvjlfourktdhxxgvonedvnsvlld\n" +
            "qk7294fl\n" +
            "sevenfivesevensevensn4\n" +
            "rnpqmrgczhllzszvkfzmcljzpthree8\n" +
            "fdcqknlctq74\n" +
            "1xnvpvfgsbslkkktxxhn\n" +
            "one5eight3zrldkdj\n" +
            "nlvgbz71fourk33\n" +
            "sixfourfour6three2three\n" +
            "7lszpqqq795nzdfxbzsqlsix\n" +
            "one8nkqdtctsjj\n" +
            "7xfphzjzndr1\n" +
            "keightwo25hmqthbeight\n" +
            "2sixdm\n" +
            "l4eight1fourfour\n" +
            "2ldzseven3eightmdmsgkrrfivetwobbzz\n" +
            "mtwoneonezdfour22two6\n" +
            "7fnjbjqdxvkntlfkhkvnzt\n" +
            "dhqsqnslccxgdd63x\n" +
            "nine6fourthree\n" +
            "7qzbrpplm9\n" +
            "pqbdbxxxggn9fivebfttnine\n" +
            "58h152eightjmjqlzjjp\n" +
            "8vjrtblqzsx\n" +
            "7sevenonesevenhqkvxxsvrsix\n" +
            "four6hcxdtwozjnpsdtpzxxninevzvsxffxpctcjbtmlm\n" +
            "3xznljnjz4ms3seven\n" +
            "8892\n" +
            "3jrzlmpnxhfivefivetwoseven7\n" +
            "onethreetjpmpvpr6threethreeone\n" +
            "one5thcfourndbphpxszjmt7eightwof\n" +
            "r5s\n" +
            "fmjzjqlnhxqhvbdvdfbdnb4\n" +
            "nine9mrqdgnkc\n" +
            "nm5jxpjgsm31stkvxjseven5\n" +
            "hplgpfrtlb8dgsbbljfdgknfvqbonexbcddflz\n" +
            "4bmfrjvj81vvnztchfrjfive\n" +
            "xvvb2nfqxdmpzjvrbmvvtmc16\n" +
            "txrfivecjq6hlgjbvzp3threefourone\n" +
            "sixlthreeeightn9hqmxhxfjrb15\n" +
            "six6eightone3\n" +
            "9six7\n" +
            "nineoneseven2eightbr5nine\n" +
            "sixqqdsdmtkgkfq9\n" +
            "3fivefiveffive\n" +
            "8eightfive2six\n" +
            "7rnlhrhlfive\n" +
            "kvkrxgkk6one2ninermqtpbbnmpdpjxc\n" +
            "nhltwonesix3five3two45sixk\n" +
            "eightsmjnzfzjk8\n" +
            "sixhxsprkfour5b9\n" +
            "vkvhvhrvbnvz7rg944\n" +
            "ccvzjppvjtthreetwoqdc4eight\n" +
            "threefive9qlg3hkhvrbdxzdthree11\n" +
            "onesevenczvffoureight28\n" +
            "three39jddkzzjninetwo5\n" +
            "63nine3sixlqnbtrq7jctmgdmk\n" +
            "zxsqngxxfd9rvjjt14978five\n" +
            "9983eight\n" +
            "sevenddfpzjp3skz\n" +
            "bzdpg73eight71ppzkeight3\n" +
            "onevphctjs4\n" +
            "twofive2jxsthree8sixqeightwozrv\n" +
            "6klpdhhsdng\n" +
            "thxtwonefive57rpseven2\n" +
            "qtcdgdfj77sixrhtczdcbp3\n" +
            "seventhree47\n" +
            "threekjqqht883\n" +
            "two3jfgsdnqbxcbzjtteight\n" +
            "5zcpgcgsixdskfszmmq9hxtknineqmhg8\n" +
            "snjs1lxkpbk5\n" +
            "seventwo7bknk9\n" +
            "rstbvlzlk1tpqjsjmhgdcvpfdqzl2bcbtn\n" +
            "3eight4six2\n" +
            "twonine8xkqp3eightgheightxplcqbvppj\n" +
            "ninevkrvzvseven6eightcmmvgzb\n" +
            "77n7fourthreecrcq\n" +
            "xlvszfhhffhmvxfour8skpvl\n" +
            "9nine3kfhgngkd1\n" +
            "sevenfivesxdxhtkmeight4\n" +
            "28four92\n" +
            "mjzm465qffive9\n" +
            "dqlghfxbkfourfivegfkmgmdgzxtm1\n" +
            "six13lrc\n" +
            "8qbvnhbplbl6\n" +
            "13lmgbfsgnxone1\n" +
            "ttdznnjsgjtwo5\n" +
            "eightfourtwotwoltjxfourone3\n" +
            "8threethreeeighthbbxfbmpj611\n" +
            "ninekpjcrvlqbmsixseven5four\n" +
            "8jmgspsevenfour7\n" +
            "6nineone5hthbrbsjrhbnn2\n" +
            "ninezzdlfiveseven4\n" +
            "fhrxvsevenlvnztq4one\n" +
            "cvmlmzz8njtfztfzfoneonejbckeight6\n" +
            "ninexdgtgjjnrb1hrhjvchm\n" +
            "63gqjvjtmzgkpbfthreesix\n" +
            "fkstfchxcbrkfivemzhfdhsffd4mnbbmgprxcgmsl\n" +
            "87rslqkvbzncfxddt\n" +
            "7fiveeightxqjhdkbbgdjksn\n" +
            "four375\n" +
            "sixftdrnbzq84688three\n" +
            "eightseven8kqdcbgtmvlsvxx24fqrfp\n" +
            "four7vprrmq91\n" +
            "six85ndzvnplxhkmrjftsixeight\n" +
            "5twofourzfdxbffive\n" +
            "4jbvmpnqcpbdfrkzone9ndcxtgsfive\n" +
            "nine3jzpsrhb\n" +
            "nine6cpqsfour\n" +
            "78kzczxbcthreesixxtdkflhzfour5\n" +
            "14sixsevennzgfnmppnmcddd9six\n" +
            "fourncvgmhfl2fivefnlndmj\n" +
            "rzgqvdgksz6six\n" +
            "23seven2rhlv5\n" +
            "9xlnnvnvccj\n" +
            "3fivethreembplpfdjnineseven2\n" +
            "jk1\n" +
            "3threevgklhnnnccrmone2\n" +
            "threefourfive4\n" +
            "qtpbdrsix67threekslkmqt\n" +
            "five3ghvqnrhtbqnvtmdlnine\n" +
            "84lvnfx9nine\n" +
            "nine7onethree46\n" +
            "vtshvtcch5kxkzgkfourrtmbq\n" +
            "5czsbzl3threeeighttwo\n" +
            "38nine\n" +
            "twovcxn9sixklflgptlkt\n" +
            "fcjpjrxdleight87\n" +
            "cfn6\n" +
            "sixfourtpzpnsvghlqp3ssptlls\n" +
            "trsjxmzvhxgvtzrhxqbb66nfp1knf\n" +
            "twosevenmdmmcjjgxj96qxrqqteight\n" +
            "sfcpfs9dpkvxrmjfiveseven\n" +
            "6dblskzfsrpcnszqtwo9rgrdkjshb5three\n" +
            "5fourfsblzr3onesix\n" +
            "gcxsc9\n" +
            "txjtwone12\n" +
            "twovpgthxxrpsevenqxpmlbrr3three5\n" +
            "csqkgmzl93xrxjs64gptsix\n" +
            "33qjjzgjtrsflgpr6\n" +
            "twoeightseven6zdtdltvzsxvlgsevensixpmxlfrb\n" +
            "gjnvdxbveightone8two\n" +
            "24vjdfhninezfvlgrdvsh8\n" +
            "ninehn1685nineone\n" +
            "twoonegsix4threeninezrsnvrltqlms\n" +
            "5cdfdldjxddrjhncxtsndl8\n" +
            "1mqg3nspfxnkfoursix9nine\n" +
            "1tfcrfpqmk1stfrrnrz\n" +
            "721dgsmsixjtxcxmj4jhkdsfj\n" +
            "9plbxnrnlgsvtshfgzbkfive5qfbzgrxzk\n" +
            "fourgjdt2\n" +
            "ninethreeqqxrjjgskm1fourseven6\n" +
            "rbrr1\n" +
            "threekrslrrqngjtwo6\n" +
            "llkbxgqp2cmnmgdfgrcshlmseightgjzs\n" +
            "66sixeightthree\n" +
            "64vdnrrqfxonespgfhzdcdrbrqone\n" +
            "threervnhkgdg7oneeight\n" +
            "nkbrvsvlzkonermsvxh65dlvxbxvlnq8\n" +
            "twozbkclqppd9txxzbvfppz3\n" +
            "two9nine\n" +
            "7vnlqfgxlmninek2two\n" +
            "qjzggvqj1ninefourrc2szbmczr\n" +
            "seven6kfkkm7\n" +
            "nqlgfzmdfsevenshvcnxdjvxveightfour9\n" +
            "seventdrqkrxkeight75qjfbb44\n" +
            "four3cxhlvthree3tcvrzk\n" +
            "six5seven2\n" +
            "3ninehcsjfstwo5xsgmkz6\n" +
            "3fourlnthree1fourseven\n" +
            "lsxzsskbsqmeightcrddxvxk93fivevfshztv\n" +
            "nxqxrsevenl3eight\n" +
            "239fourjcrffkeightfivezmfsvqvpz2\n" +
            "hprcp6\n" +
            "rklbzvhll4nstdjb7fourthreeonefour\n" +
            "9jlnthv\n" +
            "65six4dvtftwo\n" +
            "nine5five3kqvrs183\n" +
            "sixrgtckzc7nmczdx8three2\n" +
            "4six61pzjhnhpbnmsq\n" +
            "1fivembsixsevenddmrlkfour1\n" +
            "qhgxrbnfc8one2vxc\n" +
            "rdsttzt1sixonefive\n" +
            "lsdoneight5pmlztbkvzffourfour7\n" +
            "7g3\n" +
            "3sevenlnjfvms9two\n" +
            "dclkonefour5\n" +
            "tskeightwo9one25ddmdmkqrpffoureight2\n" +
            "rmkqgbh1slrtshgkgbdsftvbgm4\n" +
            "qkhxmpfzf51\n" +
            "648\n" +
            "three4gfnxzrs2\n" +
            "hmcskdltfourllp7sixfiveszgnfbpjt\n" +
            "hf27ninep1fqdbglxngkf7\n" +
            "seven6bfhtdztzvqhqnj2xfxchxpfc9\n" +
            "8vfksvbfive9lxjhcfive\n" +
            "626txvseventwo\n" +
            "1bgzkmzx1\n" +
            "nineeightlzv2l\n" +
            "8ninetwo68twohhntdvjpzfone\n" +
            "jsjfive535fdfnj3\n" +
            "fnzrsevenhcgzccslt92twonine71\n" +
            "4twothreemx\n" +
            "6vbtgjssfoneqpsrdfrbcgmrfckfourpzdlb\n" +
            "91svfsxrseight\n" +
            "nzmnpbdqjdh2four\n" +
            "blqjhjxplrxsevenonefive13\n" +
            "fivef11gtdpgbdrxnbtrfqxfb7r\n" +
            "l5fivethreenine\n" +
            "oneffcdpqmvpcdcn6six944\n" +
            "4mmfjltf7\n" +
            "29threenine26\n" +
            "8zrthtv56\n" +
            "c21hxksz\n" +
            "nqcbjkb7\n" +
            "fourxtkrn7bvpbqtcg78\n" +
            "qjvmvzbkxlseven756\n" +
            "6g31dk1mnsgxhbdvndjgvsjr\n" +
            "73eight\n" +
            "61jlzgrrpkvgdpjzbbqkxp\n" +
            "3368nineeightwodzl\n" +
            "9tlqcrxsix7\n" +
            "cmrrnf8five1\n" +
            "4three72\n" +
            "hhcghmtvznine6nineseventwo\n" +
            "22tvjnfvzshdtpxzxrnzvtwo\n" +
            "8threeqlkxrkfsevenfivegxmbhqg\n" +
            "5mzzsldbk7ninefourjfjv\n" +
            "rloneightcjhxsstwotwombktzlkdxtwo8\n" +
            "three92nine1sixeightwof\n" +
            "drxgb14twoone\n" +
            "7one7seven258nineoneighthkd\n" +
            "4four4sixninem\n" +
            "fivejkjpdbfpsttjnpkv4one8phckjllc\n" +
            "5bmeighteightgkjfkjthree\n" +
            "98lkzpdnvs7chnmkxzql\n" +
            "twosix2two15xzkpmctwo\n" +
            "951\n" +
            "four481six\n" +
            "3tdvlonefiveone\n" +
            "88fourgktxksmhninecfpljsix\n" +
            "cphlzlx45fourxjphtthree\n" +
            "6eight4gfjjdvslqv1six1kxlmn2eightwof\n" +
            "5vxrzxgdpg7vrsrxrrhncfour\n" +
            "5threethreemrzfbjq\n" +
            "ninecsg9lseven828bjttzx\n" +
            "5kqnine\n" +
            "fivetdhxq39\n" +
            "rcvlsix6pqzsggz59\n" +
            "47fnrs\n" +
            "724onesixtwo\n" +
            "tdbb7\n" +
            "sevenseven4\n" +
            "two7mlzgdqthree\n" +
            "2gxzbnlrglnvmqmzbznfngxfeightnrcrqsjnftfourone\n" +
            "fivetwovsbvrfour2ndmltmprsqkbbztwo\n" +
            "j3twoc6mmzt\n" +
            "six47nine6tkpjleightwopzf\n" +
            "sevenmshrczkdqfiverkmhlqjzqqhgppbsm58\n" +
            "pkbgvlvzckvone26rfqbmtwo6\n" +
            "sr9qsxjnine9zbc6three\n" +
            "eight4qxlmtwo27threesix6\n" +
            "fourone417oneone\n" +
            "6fpvfbrrtwoeight\n" +
            "79rj4eight88\n" +
            "6vhfivevrj\n" +
            "7tmqhchfive6jxgmqcfmq59eight\n" +
            "threeone3xqcrjzszhseven2csbflgnds\n" +
            "1qsxxxmsknhseven3nine\n" +
            "fivemqxjlggcnsngflb5qtshllseven1onefive\n" +
            "7476qfcmqqbfhvrvksfztskmzgvjjsrsc\n" +
            "twosxlbrgdtptwo16\n" +
            "kffmtjnjjk2fourtgv6rvsrzcvdrklplndseven\n" +
            "eightzhrfgpjfqgccn2khrfdzfour28\n" +
            "ninetwoxvnhfdjsxslone4four\n" +
            "92nine48b\n" +
            "ptwonefourclthree56\n" +
            "hshqjfknineeightlkdxvxcsljfptlbb6kt\n" +
            "fxjbr1four\n" +
            "nine36gqbt6\n" +
            "nsbcvzninebvlpvlx1three\n" +
            "1ltlxzlmzxhjlfvtnrrpdk\n" +
            "3jpqgspseven5qm\n" +
            "553npbeightxf\n" +
            "fourbspjfbxk4\n" +
            "238\n" +
            "xjrsdsvgncxddpmj3tlqone89\n" +
            "68bkvsslntwo\n" +
            "dxcmpjfprnthree98sbh\n" +
            "reightwoeightseven76xqfhvbkfouronegkrfvdzzdx\n" +
            "9lfpjff\n" +
            "gcvs5\n" +
            "hnctpgpxdlvklfsdfour2hnvtklhgqxhjpzknine\n" +
            "ceightwoninefivetwo9plndfive4\n" +
            "pjnzdrhtddjgllbf9f25eightb\n" +
            "fpsdpfl8cnhkjtzhfbhdftkvm\n" +
            "3cqqkflmjmpfmkk79lvkjljd71\n" +
            "bfpfmkjpnkgspsz7nine\n" +
            "threethreetmpntmpg3lfzzsrzr36plfvxv\n" +
            "nvssix83\n" +
            "dznrcvvgb8\n" +
            "csrffxrtvmpfgbkcmmdlzxneightzvfgxdpljpcnrcn5\n" +
            "9sixtxxthree\n" +
            "seveneight2kpzpvvtzq8\n" +
            "jbmmeighttwo12seven96bcvcs\n" +
            "b68pvjcsnine8\n" +
            "4vphtk7\n" +
            "mxmjvnbqseven2\n" +
            "3two2foureightxvvtxpcdmsdzvkg2mthmx\n" +
            "cxslpdtnnx5five65\n" +
            "97mp3qbkxmhl5dkphzgmpg5\n" +
            "7f11sixcnrqone\n" +
            "8fxjdjxc6drjxnhptdeightseven1six\n" +
            "sixffvgcsfourhmnrf8\n" +
            "qtpjrmlgnlkbbbr7sjcpm91five3\n" +
            "5pqv69one\n" +
            "eightnine8\n" +
            "1three8\n" +
            "39cspknxbsjhtfourpcbqsvlgz\n" +
            "5nine15\n" +
            "zgjgjfcdphnqqv4eightsixsevenkv\n" +
            "6ggfxblx47nine2onenine\n" +
            "1twoone2xfxfcr5\n" +
            "sjvpxd7ncpclnc57one1\n" +
            "4sixdgone\n" +
            "89ptctqvnpg\n" +
            "threefour1four4\n" +
            "8seven5pfeightfive8hclpxjgftc3\n" +
            "mznfsbmdtltwoqlf9\n" +
            "425\n" +
            "n51891\n" +
            "one5l\n" +
            "8ninefive2jhhbnjsvdqtlmsjgshvlvlh\n" +
            "58ggdlkpcmkgeight2vcprcttwo\n" +
            "twoseven3eightfivesevend\n" +
            "krrzfivexrmvdtbr1zvqpmthreeonenqnmx\n" +
            "2sixhjpxptnthreezkfsix\n" +
            "jchkkkgrdmkvdgksevensevenfour8five6\n" +
            "1tzbzthree\n" +
            "xkone7zvgtv5qvln\n" +
            "6fivetwohjblzsixnine\n" +
            "onelpgkpggl9nsdxtgh4tgjfgpcsn3\n" +
            "bjdxc7krrt16xbgvl\n" +
            "sevenrpftshchmkkflxseven4eightsix\n" +
            "groneightfftfvk6\n" +
            "hrcshqtxpqgxeightsix1xxxrczpcr\n" +
            "foureightthree9sdffivebdtrng\n" +
            "ninefourthree9eighttwonine7xjrsm\n" +
            "fivefour64\n" +
            "51onefivetkcdbbslzmeighttwo8\n" +
            "4rssgjpzgnczqtdrfivesix7bjxslhzthreefive\n" +
            "5kgkv7ninethree\n" +
            "84ninepsbvzkgrvqpzmtqgmcxpvgfbffns\n" +
            "fourrvdzsntddfoursevenqq54lgdrtdcq\n" +
            "4nineeightfdh\n" +
            "9twoonefour2kmnb9\n" +
            "qcvmnq13tsptksgmqj8\n" +
            "113twonine4zjsbtjkpbdsix\n" +
            "sevencvnineq6jvnshmg\n" +
            "pjhmbnjqflvp452sevenfive69\n" +
            "2three1sixninekmfcsbsevenfive3oneightg\n" +
            "six3six62onevrhtsskzrhtthree\n" +
            "5bxcmdnrf1szdgfournine\n" +
            "fourxdxmk6\n" +
            "3lsnfgffnlrqboneeight\n" +
            "9sfsv4gqhpbqg86\n" +
            "two17567fournqkmh\n" +
            "7threesevenzgxvkhf\n" +
            "vlmz7sevenfourfour8bqzdrdktklfivefq\n" +
            "xxsvcqqeight6flrffzxpfourkzfstj9\n" +
            "fourlzpdxg3knxgl\n" +
            "msb246fourlc1crhlbjgdgr6\n" +
            "1q1cmrmqponeightd\n" +
            "twoeightncz513\n" +
            "nine1nine\n" +
            "8sixonesixnine\n" +
            "193sixthree2rgthk\n" +
            "tvhqp44hmjhzvmhgrbprgttgrt\n" +
            "52bdszlvsvgzonefiveeight\n" +
            "sdxnpkllmnninethree5jxsgkdbmknfrfvthree2\n" +
            "six23hdzmppf67threeseven\n" +
            "eight5nine76vbggdlp\n" +
            "4onevrxnnbszk\n" +
            "9ninezhdsfbfive12\n" +
            "sixnine5xqmkmthz\n" +
            "fiveskklnrr13sevenfour3nqs1\n" +
            "sixqcxqnjxxzqmdlqtwo83\n" +
            "8eight7\n" +
            "9psvqdzpchr\n" +
            "492jseven1\n" +
            "xrccslcthreetsnfoursixsixsix1\n" +
            "gskqmvnclfgxbtcq9hsix\n" +
            "5two4twofive\n" +
            "sqqhrvtszzjs1vfskhsdsvvhlskn\n" +
            "nineseveneightcjcgnb9three3xfkst8\n" +
            "ktwone4one73\n" +
            "five6xncdddspkcbgklzlzn687\n" +
            "xgnlvnskgklcpdqvks2\n" +
            "zscmhb7mrrshccm\n" +
            "five8hplscnineeight\n" +
            "2hrgc86dsgjbvsrv9\n" +
            "8lncmqrxcnm9ctpxjxlz8\n" +
            "jdqt39336\n" +
            "1gntnqbstzrnine5cqlrrtfllb13kfleight\n" +
            "3jscjlvvkd89\n" +
            "5nineseven66nine6twoonetwonek\n" +
            "sevenxrqj4bfivesix1\n" +
            "8msix8\n" +
            "six6ninesevenfourbttvtt66\n" +
            "4cmvvdfdgqphjzleight\n" +
            "55mltlnxc4dmcrhjsjc8seven\n" +
            "26197jtlvpsixcmzkslvzh\n" +
            "rjzn2\n" +
            "krlvgxone54hdddkspmfkpnzcbtbz\n" +
            "four2two2\n" +
            "one5vjjs3one6six\n" +
            "6cmt88three\n" +
            "reightwo7lrjqxbmgjj3seven2\n" +
            "ntrkndgqzpfkjrone9\n" +
            "5dvktjpseightxxmbtrm\n" +
            "four6seven9936six7\n" +
            "fourhqstnjbbdscjngp5fpxmg\n" +
            "77five\n" +
            "qrzg9five1qqcsonekgvckmmpfx6mpxd\n" +
            "qzjqstcll7donekkpmkgpdthkjclrpth\n" +
            "14seven\n" +
            "bpbfnnq4rpppcjfeightsfcsqzg\n" +
            "2one7eighttwo2vhzhjpgg9xhsdvlgxf\n" +
            "eightonepn38ztcqzbthjz8\n" +
            "lnsix7eightskqhrbx\n" +
            "sixvnpkpsdzsbjgjkbxreight8five4\n" +
            "vfrvkmnvnhk5one\n" +
            "eight9nine7\n" +
            "oneone5\n" +
            "7584zprfmjtwo1\n" +
            "4szpqtwoflcr9bhtthreeeight5\n" +
            "385\n" +
            "ninekdqknptxhsevenmrmjzqjvnppsrgbkv9jeight7\n" +
            "5fs1sixeightthree\n" +
            "sevenxkvxzqhckfourninetwo3eight\n" +
            "9eightgfjvv\n" +
            "xh8\n" +
            "brbs3fiverzrtwo4jtdsvrljxone\n" +
            "qcvfnlvfivetwofourgsdlcmkb5\n" +
            "klnsqmblkffsq4threetwo6\n" +
            "nine4eightx8eightwohrk\n" +
            "c1\n" +
            "sevennine55eightttlbshbfive3\n" +
            "6ssmtjnxsixthreengrlndcb3\n" +
            "vgpq8sixsix\n" +
            "96xhrnine9\n" +
            "grpsjz1zqzthreeone2four\n" +
            "r6twosevenrdmczdz\n" +
            "jdjz4ninefour\n" +
            "one88\n" +
            "ninerzdfc8rxnfbpndznctqd4tlb\n" +
            "cshoneightnbdfmpdh2fnvjtxtshseven\n" +
            "gtpljthree1six\n" +
            "63eightfournncq\n" +
            "twoonegsdpfkfqdf7\n" +
            "xccnnscfivexbqmxfouroneeightgvndxgnine3\n" +
            "mktvsff76bfqkq9fivetwo8lv\n" +
            "3four5\n" +
            "qhdgmcninethreevssbxqbsd35\n" +
            "one6mprksdcz6hpxhrdznfpkmp\n" +
            "six55ninernnmmlgmblttbgph8pqrjtjhtdj\n" +
            "jnpbmnbqonemjcsgbg1\n" +
            "9eightfourmkknzgmqh7two\n" +
            "7five9\n" +
            "2eight44skdlfbhfsshpvhgfseven\n" +
            "2cqrzrhbfn\n" +
            "three8419two7\n" +
            "rvpblkzgkmxkghsbfn3one\n" +
            "nine58\n" +
            "74spkcfzsdmkf2six1\n" +
            "2threeseven\n" +
            "sf84qnthree5bmxnrmqff3seven\n" +
            "oneonecxxv96\n" +
            "gpdbgxgjqzdzlxgqphdr63twofourkspvxmvrfx\n" +
            "fivesflg9fivesixonexfb1\n" +
            "8pc56fourqpqmfour2eight\n" +
            "3qvgqqldcr8\n" +
            "tssixfourlbqstcmj1\n" +
            "pf2sixpzxcpmxtp7twoseven\n" +
            "5429\n" +
            "drtlhzlqltwosevenfivetwo29\n" +
            "eightlqtfronebqhdh1nineonembxnbpgg\n" +
            "vlvnzcpbpqeightjspbbqqeight6\n" +
            "sixkkmgcnhdfldplzk3five\n" +
            "93ninekcmgjm8ckqjdz\n" +
            "3dmskrqjd9\n" +
            "five5threefivesix\n" +
            "lgvbpdnp8oneeight7eight\n" +
            "seven37\n" +
            "2onesixtgbqbnn9eight\n" +
            "5ndhfjrvt5fivetrhzsmqtwo\n" +
            "bdcrhzdr33ninefive9\n" +
            "cgsdzcninetwofive6one\n" +
            "fiveljbtcqcqdglvjnd8onefour\n" +
            "two2b5lzbjsqx7\n" +
            "three593sevenfivetwovptpnmxffrkbsp\n" +
            "sixonesixthree8btmzlnkvxt\n" +
            "2jf59\n" +
            "eightfivethreenine57qpdkcfr\n" +
            "eightsix31threeeight512\n" +
            "fourseven2twoninenineeightone\n" +
            "pqtnqdtsix1\n" +
            "3zpnvhlsjcmcdvzzlqp5\n" +
            "sixvnmhckrzxfmjglc964nine\n" +
            "mftxdnhdzmfnrgvvz59nlhhvr7spjrh\n" +
            "eightls148mmvsjjldzlmvxjd\n" +
            "3five5mlfhszsevensixthree\n" +
            "4zpllkssevenfourtgbhdkltwoc\n" +
            "ffourhnjhmtxxfjg511\n" +
            "63jddsfqsmjdmgxnthree3four\n" +
            "eight3onetwotwo7\n" +
            "fmfour9tvfourfourtwonef\n" +
            "qseven91two2fgnzcjnm\n" +
            "rpzmsseven1jcxvxgnvthreeeight\n" +
            "onefourrflrntpkskseven1kthreetwo\n" +
            "5lpmhn1six\n" +
            "ttvdgvf67btpqbslt\n" +
            "3twovkbrhqsmv2lzggdlbfvgonenine\n" +
            "rstknqvqtwo55sixjpzmgjsm\n" +
            "nkgfnrxzj7jszsixfiveeightsixfourflqlzmhl\n" +
            "sevenbbbmdgbv9oneightqg\n" +
            "mzmksix42oneonexxmndklncn3bqj\n" +
            "3xxcsfonefour\n" +
            "1threeeightnine46zzscxblntplpd\n" +
            "6four77sneight\n" +
            "pcjxrxtwoseven71threethree\n" +
            "5spmqztljvbtthreefivenineonesl\n" +
            "6zlkxrbhlgf6\n" +
            "228\n" +
            "2seventhreesixfoursrhxxrcd\n" +
            "vhkkr33\n" +
            "twokzcchqdmpf3\n" +
            "qrz9\n" +
            "8lfkxtknx\n" +
            "76n\n" +
            "dpxthreeqgtjsqs33pzjxgrmtck\n" +
            "1xhhdhqv6sixlcgfour\n" +
            "four9chmvmrqmfq\n" +
            "one5cvxtvjc96three3\n" +
            "one6eight\n" +
            "sevenxdncpgzqqv6five9\n" +
            "fnlrctrph4mpdninetwo4threedm\n" +
            "one3nine5two\n" +
            "8prrdscmtgfivecsnxjrpssix56\n" +
            "foursclkcvrkvkhrbnnchlsbllfive6djnprhmkxfnine\n" +
            "five2twojknineddzszxsgxxgzfour\n" +
            "9532chktx5\n" +
            "two47\n" +
            "42sscxflsevenjssjmzn3xgzpvfsneight\n" +
            "7fltzgtkmqkgjj\n" +
            "1one5six\n" +
            "6gstggspddlninezrzcl5eightqdvjlgz\n" +
            "eight2stxftmtsbn\n" +
            "vqpqvbjvgklxrtvnkgsvlljgxlpxthkeight8fp\n" +
            "sixpjhzscgthree8eight\n" +
            "vgxfxhssbsixfivehxllx9\n" +
            "nrszzljfrthree8\n" +
            "dvthfklrvtworxtvhljnsqnbcnpj5eight53\n" +
            "76threeqclnine\n" +
            "eightvdc7one2four\n" +
            "46five1threeeight3six\n" +
            "five52k557sixxctdrb\n" +
            "hk2twoggmfchleightxnshxrcvncbxvrzhone7\n" +
            "21rpnnttwo4fivefivedvtpfmnbmg\n" +
            "onetkgkv14sixdjfznpdrvl\n" +
            "onezctthreemfnqcczxpffz2six5\n" +
            "kzeightwovrtjp94vhn9mjlrxqm9xdzbvgqfqt\n" +
            "34one17hl\n" +
            "9332r\n" +
            "zeightwottpsrgnljcmnglbfsxdkgffrlgm6jnzvkxn9\n" +
            "pmzdljpgsix7\n" +
            "zmhxkpskqzgrkptwofour4\n" +
            "pkoneightsix7\n" +
            "9695tfivexmspcgz\n" +
            "ninerrlfckbs7vcmbhkninelbhfclninesevenbppk\n" +
            "78k2qhvkzgkgkskhfiveone8\n" +
            "ndxnqczhlkdvd97threeseven\n" +
            "jmmdfvftbeightone8eight1twosevenseven\n" +
            "five9six98grthvvqdjbrkxn1\n" +
            "4qxvqfrkgnfcxkkdm1mnczs\n" +
            "n3b\n" +
            "three9bzfour57\n" +
            "8threexkglxf2\n" +
            "onedxfivedxvgxjmzkone3kbmplxbkdnpknjzrbmt\n" +
            "nine3two9fivefrmjgxkrtrmzh\n" +
            "tlgpkzfdlnine9fivezdl\n" +
            "9fourtsnhlf5ljxrhflckjrrzfjbndhlcbv\n" +
            "3tthree6zqrhbpqczsixrgvlcpm5\n" +
            "twosixnzqtvhhnm8\n" +
            "five6one6\n" +
            "4fournine946nine7\n" +
            "one8rzlnlcvdseven4seven\n" +
            "tnmkgnbrzg5nmlqsevenone7oneeight\n" +
            "eight985sjrfjdhtkrbd\n" +
            "4threexlm6twoone5mthree\n" +
            "four8fiveghddxqlp\n" +
            "1kjtrpktpkq\n" +
            "2grqpqfsclsgdzmkglxbzxcshrs811one\n" +
            "9seven94ffkfdmvxr\n" +
            "8tvnnbpj7bjmvlnnj\n" +
            "sixthreeflggjxmlk54\n" +
            "6five6ninecjdmkggsixnine\n" +
            "sfjlhbbx6onexxjsix4z\n" +
            "9bbnhtpgbntzlxct85\n" +
            "2bltznvqgs8sixsix\n" +
            "nms7vst8\n" +
            "eight9vnrqbv\n" +
            "two663\n" +
            "1h6prckcqdqn\n" +
            "2ninesevensixtwogkvtjrp6rbgc\n" +
            "sbsncmpsixhfvttwo27fsb\n" +
            "fourtwoshvjffjdeight83knlxbdjphsn\n" +
            "bkbhjcgkjbcgjsix1\n" +
            "cfkpjctlnztlsgjonehrmvtl7vksr\n" +
            "8eightphhd\n" +
            "6eighttwosix5one\n" +
            "8dtnqgtrddjfqmlrptphfxkcgoneeight7\n" +
            "32eightjfgtqjllmxtf6s\n" +
            "twovqnctjcvsdfjbhtnzccd2gshchnhrpx\n" +
            "twovqqpbrf9\n" +
            "four4onelkjf15psdspgvvdfcvmnkhmfive\n" +
            "xdpg4ninetsbrmpqfive\n" +
            "fiveonefive19\n" +
            "46qtppz\n" +
            "twoseveneighteight72\n" +
            "fivefourthreesevenbxtpqctslbkeight2qmvgth\n" +
            "355ncxjffxt\n" +
            "eight4zslht5six\n" +
            "sdnsrghmbxxjhjqd1njqjcghsspmggzd2\n" +
            "vcthxnqqkvqsjrkxrs71onetwo\n" +
            "fivexcjvm9\n" +
            "3kddthreehfhjmq9ninesix6\n" +
            "rclqzddvxtm2nineninethreefour\n" +
            "vlfgxbkdgnxrsprd386onethreetwo\n" +
            "5sixjscbvzkxtl5fourone\n" +
            "317dnqnqntwo65jnthjbxnfive\n" +
            "mxtwonethreetwo2ninefour35lnhczqfpt4\n" +
            "nlctnjrr9twopthreefmxgjeightwofqh\n" +
            "nz8threefourbhcjvssgcnine\n" +
            "sevensixzspvzjseven9\n" +
            "six6onetwocnvmjfour4eightone\n" +
            "7xfd5qlmtzhhgr\n" +
            "8twonesch\n" +
            "nineqvlsrfpdn2\n" +
            "ptrfgdnine7gpxsix\n" +
            "pfx4sixfoursix4fivesix\n" +
            "68lqzp\n" +
            "nine53jmtsxjptgmzpfoureight31\n" +
            "two1msjf8\n" +
            "gpgrpptthreetwomfrmkszrv8\n" +
            "3five4\n" +
            "threelqgs2kjvlsbmjkf\n" +
            "4fourzgqkfhqhvhpgfkt\n" +
            "jnlbcbgrp7\n" +
            "onecdcmbrqxxlpbd1rthree\n" +
            "99mbfdcgbhv\n" +
            "nine6cvmfourfivesixhcsqfpxkdk\n" +
            "eighthjbqsbz6ndpkdlnpmpxqvpmsrbvksnnleightnzxmjg\n" +
            "gvvpnfzbb7zxfschnrteight6two5tnp\n" +
            "sixrctqxdpkxpfdkglvthreenine47rzs\n" +
            "jtwonefour8rkmtclhlf97fqpjmggtztwo\n" +
            "slmfjkfgbjt6\n" +
            "8lbh\n" +
            "eightnqtfvvm2\n" +
            "vseven31\n" +
            "one54qrnzfrbdqfive\n" +
            "8twokfivel9\n" +
            "vfcsqvxkdxfiveqdvgqdmstn5\n" +
            "5l63\n" +
            "two8fourzskrqbcszfzbchlh9ldcp6\n" +
            "hqhszsgmqzlksq5\n" +
            "sb6fivefourpmtptjtkzhbxjjnqsixkt9\n" +
            "twohrktppz5sevenhppmnjzlrkdqddsgs\n" +
            "two37ninefive\n" +
            "fourllczb9\n" +
            "sixfourone83two\n" +
            "ktgpc7\n" +
            "fjsnkdj6sixsixtworlhgnbqlbm\n" +
            "51zscxpk6onesevenjxxzcp6hqrtjmhqpk\n" +
            "dmxfcfmfsbfpjfive4\n" +
            "one47\n" +
            "9jdlkcpzsevengfddvzxdnfkxf8\n" +
            "fourdxnine3four39\n" +
            "nine1one7fjcjjckngthreec\n" +
            "5dlqjlbpt\n" +
            "twooneeight9gf6zvtsqvrlnf\n" +
            "three3six7\n" +
            "3jnhfivethree\n" +
            "1pzdqvjftwofive348\n" +
            "four7kcrqkf9\n" +
            "9cxglsdg\n" +
            "twobgmghbrqdngthreervxjbmp7xvrskhfcf\n" +
            "cpvhhkgmftttdtwoqfncthree1tzlbqcr5\n" +
            "kmxqkfmlgtmztzpr74ninebqgcjkksljrphc\n" +
            "mrsmtdhpsixslxg9five7\n" +
            "53two\n" +
            "xpfzv3\n" +
            "twosdjhone551twozgqc4\n" +
            "89fourfournfhc\n" +
            "five7chqddxtwo1tjmlhqsix\n" +
            "dkrnxgh5xqzcnjzrhg\n" +
            "lcvfqpglmntwo1sixthreevdndckjgpkzpsp\n" +
            "foursixnineseven1llbdvckff\n" +
            "6four15fivettfivefive\n" +
            "684cfnqfxkxgeightnfgqqmthreelbfxxdsmn\n" +
            "fourdcxxseven28hxqqfhxtd\n" +
            "1threegjffmjrfxppnsqthree\n" +
            "3khnfmcmtj33\n" +
            "9ninejvdl88\n" +
            "3four9seven8fourmpjpkn7\n" +
            "tmfourkc1sixfournglfl\n" +
            "24xgscdtfxhttglvhczrstpfcjvnine2fiveone\n" +
            "psqoneight4twojxkcvgdteight1rhcgmkmmjbbnzdhqj\n" +
            "sfrgqk1two\n" +
            "fiverzjbzssone4nineninefive\n" +
            "twonineonergqsg2eight7eightwolf\n" +
            "rztthree6sixsixxsxtvjthree\n" +
            "78fourcvthree\n" +
            "17hjphkdthree\n" +
            "tdprffbgqseven7\n" +
            "58eightbchzffmkhh8twofivethree\n" +
            "zpbfstbb71hgldfkrvfourthreeonesixfour\n" +
            "fiveseven1eightnine\n" +
            "four8nine4vxpfpgxtlfhcrndscfgn4seven\n" +
            "pgtznpnqvm1one1dfsix16\n" +
            "ddffoureightpmqkznnseven75two\n" +
            "6lklqx1sevenzhfdb1\n" +
            "mq113scstpnnveightfive3nine\n" +
            "threetwox79\n" +
            "284mrsixthreefour\n" +
            "1seven7zk4lldz2\n" +
            "271nine2fourfive9\n" +
            "fourthree37xxkvlgsixzpkblnine\n" +
            "xbbnj2eight33\n" +
            "seven5sevenonekzpnhzx\n" +
            "247xgmlnntrcsixbstnine\n" +
            "3ninezxtbqbfgtdjpgmjv\n" +
            "tvxkssrfthree3\n" +
            "fourfoureight12\n" +
            "onefdszsvrzt2fdeightzkbmz\n" +
            "cqrqkfgb3sevenqtqntxxhqlvrcthreefour\n" +
            "2one5ptslgxsp4six4two6\n" +
            "rskmbsfglone913vlmqtmpvfsevenp\n" +
            "7c\n" +
            "nkzrdb66crhk\n" +
            "onevdttzljsmzvvhlf1tzqsqnnchdxbmngtlzzjdszvlvfzhx\n" +
            "eightbtstrjzmfmzvcgsbgfxfour4one1\n" +
            "pttthttfftkp41\n" +
            "two9rlqrxvsevenfive\n" +
            "v2four4\n" +
            "two2one\n" +
            "rdvhthhzrmeight5jtgf\n" +
            "flshgbbtztkjfive8\n" +
            "7sfc181fivefive\n" +
            "fivenine1bfnchprbsix\n" +
            "six2zpqshtndsgsevenone3one4\n" +
            "fq8\n" +
            "seven4eightvzfq7kthqh\n" +
            "4vxtllmlnine8gsqkngfdzeight\n" +
            "vhfzmbgseven5\n" +
            "skqfzlconefivertzchfkvthreeeightfive22\n" +
            "72oneeightone\n" +
            "7ccs8vjx7vvszsn\n" +
            "xrtmgqk95five849\n" +
            "threebqeight8hg\n" +
            "drdhjjtdrdxonenineninefourfkzrrggvz97\n" +
            "8xxldtmdctllqssgdqp83\n" +
            "dfqrjzv9rqbtn6\n" +
            "3ninenhgqkglfvjbmgcdrsbhfournine\n" +
            "five821\n" +
            "54foursix7pv2qsix\n" +
            "7197threescjkqhpqvzgjthpmcgtzrcd\n" +
            "ltpzstwo78fivefourstwox\n" +
            "mcqcmxxzcmpzrz4ntgnsgqbqjmkzpqvxtvsixrzzr3seven\n" +
            "foursixfourzrnxsixgpx7eight\n" +
            "41448sevenhxjpbvhvlmqrpjsvhblts\n" +
            "1geightgtxlzdmpprjvg856five\n" +
            "2tgrll648four\n" +
            "3pkcd6eight948\n" +
            "94sfznqjqlkvfjgczm\n" +
            "twockgseven4seven6bp\n" +
            "sixsix6eightsixeight\n" +
            "nine3threenpsmshnchm\n" +
            "threemqfptponesevendbjs17\n" +
            "2ninehnsnnvj21fkeightwodmz\n" +
            "jcptspngbc38nvtnrmvqtwo1\n" +
            "6qsmcvfoursmlsevensix4lkpxxcnk\n" +
            "xmtjrsrkjd5\n" +
            "7psvffqn4\n" +
            "3sh\n" +
            "jdklghtbz1eightrhvfmnlknlghg77\n" +
            "62tbtjfkltkdrxsxhhxpvbfvpnrpflh\n" +
            "fpctmmvvnbftv2\n" +
            "nkxmdshm5twoseven672\n" +
            "88788jnscmpqr66sxcjx";
//    static String letter = "one,two,three,four,five,six,seven,eight,nine";
    static Map<String, String> numLetters = Map.ofEntries(
            Map.entry("one", "1"),
            Map.entry("two", "2"),
            Map.entry("three", "3"),
            Map.entry("four", "4"),
            Map.entry("five", "5"),
            Map.entry("six", "6"),
            Map.entry("seven", "7"),
            Map.entry("eight", "8"),
            Map.entry("nine", "9")
    );

    public static void main(String[] args) {
        int result = 0;
        for (String s : input.split("\n")) {
            StringBuffer f = getValue(s, false);
            f.append(getValue(new StringBuilder(s).reverse().toString(),true));
            result +=Integer.parseInt(f.toString());
        }
        System.out.println("OK: " + result);
    }

    public static StringBuffer getValue(String input, boolean isReverse) {
        String[] n = input.split(""); //array of strings
        StringBuffer f = new StringBuffer(); // buffer to store numbers
        int nLength = n.length;
        for (int i = 0; i < nLength; i++) {
            String s = n[i];
            if ((s.matches("[0-9]+"))) {// validating numbers
                f.append(s);
                break;
            }
            String temp;
            if (i + 2 < nLength) {
                temp = n[i] + n[i + 1] + n[i + 2];
                String rsTemp = isLetterNumber(temp, isReverse);
                if (!rsTemp.isEmpty()) {
                    f.append(rsTemp);
                    break;
                }
            }
            if (i + 3 < nLength) {
                temp = n[i] + n[i + 1] + n[i + 2] + n[i + 3];
                String rsTemp = isLetterNumber(temp, isReverse);
                if (!rsTemp.isEmpty()) {
                    f.append(rsTemp);
                    break;
                }
            }
            if (i + 4 < nLength) {
                temp = n[i] + n[i + 1] + n[i + 2] + n[i + 3] + n[i + 4];
                String rsTemp = isLetterNumber(temp, isReverse);
                if (!rsTemp.isEmpty()) {
                    f.append(rsTemp);
                    break;
                }
            }

        }
        return f;
    }
    public static String isLetterNumber(String input, boolean isReverse) {
        String temp = input;
        if (isReverse) {
             temp = new StringBuilder(input).reverse().toString();
        }
        return numLetters.getOrDefault(temp, "");
    }
}
